# Generated by Django 4.1.3 on 2022-11-29 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snack',
            name='discreption',
            field=models.TextField(default='apple'),
        ),
    ]
